### PR TITLE
added stats.py module for obtaining system/hardware details

### PR DESCRIPTION
**Pull request by Ansh-Sarkar**
Signed-off-by: Ansh Sarkar <anshsark18@gmail.com>

### CODE REVIEW

**Comment by Ansh-Sarkar** [comment]
@prashantsengar have added the stats.py module. requirements.txt is up to date. please review.

**Comment by prashantsengar** [comment]
Cool work @Ansh-Sarkar ! 🎉 Looks good, I'll review once and let you know. 
Also, did you format it with black?

**Comment by Ansh-Sarkar** [comment]
Yes @prashantsengar i have formatted it with black. Looking forward to your review and approval. Thank you.

**Review by prashantsengar — CHANGES_REQUESTED** [review]
Hey @Ansh-Sarkar the code is fine. But there is an issue with the requirements.txt file that you have created.

I think you have used the good ol' dumping method of `pip freeze > requirements.txt` but you did that without creating a virtual environment.
This has resulted in a long list of requirements being written to the file that you had installed earlier. 

**What to do now**
1. Create a virtual environment using `virtualenv` (https://pypi.org/project/virtualenv/) and activate it
2. Install only the required libraries
3. Then do the dump of the libraries.

**Comment by Ansh-Sarkar** [comment]
Oh ok. My bad. Thank you for the info. Will do so at the earliest .

**Comment by Ansh-Sarkar** [comment]
@prashantsengar sorry for a late follow up. Have made another requirements.txt file using the virtual environment. Should I close this PR and go for another one ?

**Comment by prashantsengar** [comment]
@Ansh-Sarkar yes please pull the updated code and send a new PR

**Pull request closed without merging**
